apiVersion: v1
kind: Star
tables:
- name: User
  metadata:
    root: true
  definition:
    type: graphql
    url: 'http://localhost:4020'
    query: 'users'
  links:
  - to: 'Location'
    # as: 'location2'
    sameAt:
      address: address
    onlyOne: true
- name: Location
  definition:
    type: graphql-opencrud
    url: 'http://localhost:4021'
    query: 'locations'
  